import React from 'react';
import { Bot, ListTodo, FileCheck, AlertTriangle, ShieldAlert } from 'lucide-react';

export default function MeetingSummaryCard({ summary }) {
  if (!summary) return null;

  return (
    <div className="saas-card rounded-xl border border-slate-200 p-4 shadow-sm bg-gradient-to-r from-white via-indigo-50/20 to-white">
      <div className="flex items-start gap-3">
        <div className="p-2 rounded-lg bg-indigo-600 text-white shrink-0 mt-0.5">
          <Bot className="w-4 h-4" />
        </div>
        <div className="flex-1">
          <div className="flex items-center justify-between gap-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-900">AI Meeting Summary</h3>
            <span className="text-[11px] font-mono text-slate-400">Generated by Agent</span>
          </div>

          <p className="text-xs sm:text-sm text-slate-700 mt-1 leading-relaxed">
            "{summary.summary_text}"
          </p>

          <div className="flex flex-wrap items-center gap-2 mt-3 pt-2 border-t border-slate-200/60 text-xs">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-indigo-50 text-indigo-700 font-medium border border-indigo-200/60">
              <ListTodo className="w-3.5 h-3.5" />
              <span>{summary.action_items_count} Action Items</span>
            </span>

            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-blue-50 text-blue-700 font-medium border border-blue-200/60">
              <FileCheck className="w-3.5 h-3.5" />
              <span>{summary.decisions_count} Decisions</span>
            </span>

            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-amber-50 text-amber-700 font-medium border border-amber-200/60">
              <AlertTriangle className="w-3.5 h-3.5" />
              <span>{summary.risks_count} Risks</span>
            </span>

            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-rose-50 text-rose-700 font-medium border border-rose-200/60">
              <ShieldAlert className="w-3.5 h-3.5" />
              <span>{summary.blockers_count} Blockers</span>
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
